attributesDict = {
    'BACKGROUND_OLD': ['GREEN', 'MAGENTA', 'LIGHTGLOW', 'GRADATIONDARKPURPLE', 'sand', 'DARKERGLOW', 'GGREEN', 'PURPLE', 'LIGHTMAGENTA', 'AURORA', 'GREY', 'AURORAA', 'SOFTRED', 'RED', 'GRADATIONRED', 'DARKBURGUNDY', 'GRADATIONBLUE', 'GREENOUTERGLOW', 'GRADATION', 'GRADATIONGREEEEN', 'GREENOURGLOW', 'SPACE', 'YELLOW', 'BURGUNDY', 'BLACK', 'ARMYGREEN', 'BRIGHTGLOW', 'YELLOWDX', 'MAGENTAX', 'BROWNGSLOW', 'MAGENT', 'YELLOWX', 'TAN', 'CREAM', 'BLUEES', 'LIME', 'WHITE', 'PURPLEGLOW', 'STAR', 'ORANGE', 'BLUE', 'BRIGHTRED', 'BROWNGLOW', 'GRADATIONBLUEx', 'GRADATIONLIGHT', 'DARKGREY'],
    'BACKGROUND': ['Neon', 'LightPurple', 'GlowBrown', 'DarkPurpleGradation', 'Sandy', 'GlowBlack', 'GreyGreen', 'Purple', 'LightMagenta', 'AuroraBlue', 'Grey', 'AuroraPurpleBlue', 'Salmon', 'OrangeRed', 'RedGradation', 'DarkBurgandy', 'BlueGradation', 'GlowKellyGreen', 'AstarGradation', 'GreenGradation', 'GrassGreenGlow', 'Space', 'YellowGreen', 'RichBurgandy', 'BlackNight', 'ArmyGreen', 'GlowTeal', 'UnicornGradation', 'PurplePinkGradation', 'GlowRedBrown', 'BlueGreen', 'OrangeRedGradation', 'Tan', 'Cream', 'RoyalBlue', 'Lime', 'IceWhite', 'GlowPurpleRed', 'SuperStar', 'OrangeGradation', 'SkyBlue', 'HotRed', 'GlowDarkBrown', 'FocusBlueGradation', 'NightTimeGradation', 'DarkGrey'],

    'ATTIRE_OLD': ['Starwarsjedi', 'Astronoutx', 'BeachtshirtPURP', 'JACKETGREEN', 'Subzero', 'SPARTA', 'Vampire', 'Starwarsbeast', 'Basketballtosca', 'NA', 'BaseballPURP', 'Doctor', 'SamuraibushidoPURP', 'Chigevara', 'Princepersia', 'JACKET', 'Samuraibushido', 'Baseball', 'cyborgred', 'Thor', 'BasketballX', 'Terracotta', 'Bhagatsingh', 'SubzeroSS', 'Basketball', 'PrincepersiaQ', 'einstein', 'JACKETP', 'SINGLET', 'SubzeroRED', 'JACKETT', 'Firefighter', 'JOKER', 'Arthur', 'Godofwarkratos', 'rambo', 'Astronout', 'Cavemanflinstone', 'cyborg', 'Matrixmorpheous', 'SubzeroTOSCA', 'Pirates', 'Clown', 'Basketballgreen', 'cyborgblue', 'cyborgyellow', 'Zeus', 'Beachtshirt', '12clotheinsteinb', 'Yeti', 'Tuxedo'],
    'ATTIRE': ['Jedi', 'AstronautRed', 'BeachShirtPurple', 'JacketGreen', 'SubZero', 'Sparta', 'Vampire', 'Beast', 'BasketballTeal', 'NA', 'BaseballPurple', 'Doctor', 'SamuraiPurple', 'Che', 'PrinceChocolate', 'JacketBrown', 'SamuraiRed', 'BaseballRed', 'CyborgRed', 'Thor', 'BasketballRed', 'Terracotta', 'Bhagatsingh', 'Scorpion', 'BasketballWhite', 'PrincePlum', 'EinsteinSweaterGreen', 'JacketPurple', 'Costume', 'SubZeroRed', 'JacketBlue', 'Firefighter', 'Joker', 'Arthur', 'GodofWar', 'Rambo', 'AstronautBlue', 'FlintStone', 'CyborgLime', 'Morpheus', 'SubZeroCyan', 'Pirates', 'Clown', 'BasketballGreen', 'CyborgBlue', 'CyborgYellow', 'Zeus', 'BeachShirt', 'EinsteinSweaterBlack', 'Yeti', 'Tuxedo'],

    'BACKATTACHMENT_OLD': ['NA', 'AXE', 'SHORTSWORD', '11Bazooka', 'N/A', 'WINGEVIL', 'LONGSWORD', '12shield', 'KATANA', '12carrierbag', '12Golfbag', '11angelwing', 'GRIMREAPER', 'AX'],
    'BACKATTACHMENT': ['N/A', 'Axe', 'ShortSword', 'Bazooka', 'N/A', 'DemonWings', 'LongSword', 'ShieldSword', 'Katana', 'TravelBackpack', 'GolfBag', 'AngelWings', 'Scythe', 'DoubleAxe'],

    'BODY_OLD': ['SILVER', 'PURPLE', 'TOSCA', 'GREY', 'GREENZombie', 'RED', 'BROWN', 'GOLD', 'REDBLACK', 'PURPLEZombie', 'LIGHTBROWN', 'PINX', 'YAKUZAABOLD', 'Zombie', 'YELLOW', 'GREETOSC', 'YETI', 'YELLOWZombie', 'YELLOWDARK', 'BLUE', 'YAKUZADARK', 'GREENCREAM'],
    'BODY': ['Silver', 'Purple', 'Teal', 'Grey', 'ZombieGreen', 'Red', 'Brown', 'Gold', 'RedBrown', 'ZombiePurple', 'Brown', 'Pink', 'YakuzaBold', 'ZombieLime', 'Yellow', 'TealNavy', 'Yeti', 'ZombieYellow', 'GreenGrass', 'Blue', 'YakuzaDark', 'Green'],

    'EYE_OLD': ['BORED', 'BLUEEYE', 'PURPLES', 'REDEYE', 'boredeye', 'WINK', 'BROWN', 'scare', 'EYE', 'angryeye', 'FUNNY', 'funny', 'PURPLE', 'TOSCA'],
    'EYE': ['Fire', 'Blue', 'Pink', 'Red', 'Bored', 'Wink', 'Brown', 'Scary', 'SkyBlue', 'Angry', 'Funny', 'Funny', 'Purple', 'Teal'],

    'MOUTH_OLD' : ['BASE', 'TONGUE', 'HMMM', 'Smokepipe', 'Smoke', 'medicmask', 'NORMAL', 'Pizza', 'SMILY', 'NORMALL', 'Knife', 'Bandana', 'Bored', 'Huh', 'SMOKEPIPE', 'ROAR', 'Sad', 'CRINGE'],
    'MOUTH' : ['Based', 'TongueOut', 'Hmm', 'Pipe', 'Cig', 'MedicalMask', 'Normal', 'Pizza', 'Smile', 'SingleTooth', 'Knife', 'Bandana', 'Bored', 'Huh', 'EinsteinTongue', 'Roar', 'Sad', 'Cringe'],

    'ACCESSORIES_OLD': ['BRACELETblue', 'gangsterrings', 'WATCH', 'NA', 'NECKLACE', 'BRACELET', 'BRACELETtosca', 'N/A', 'BRACELETpurp', 'BRACELETT', 'Gangstergoldchain', 'PURPBRACELET', 'NOSERING', 'Scarf', 'earings'],
    'ACCESSORIES': ['BraceletBlue', 'GanstaRings', 'Watch', 'N/A', 'Necklace', 'BraceletYellow', 'BraceletTeal', 'N/A', 'BraceletPurple', 'BraceletGrey', 'GangtaChain', 'BraceletNight', 'NoseRing', 'Scarf', 'Earings'],

    'EYEGLASSES_OLD': ['Electrisparkthorred', 'FramelessGoogles', 'NA', 'DGlasses', 'Electrisparkthor', 'N/A', 'CLASSIC', 'ORANGE', 'PAT', 'Blindfold', 'Oneeyeoldglasses', 'CHILL', 'Flame', 'Thuglife', 'VR'],
    'EYEGLASSES': ['ElectricRed', 'Goggles', 'N/A', '3D', 'ElectricBlue', 'N/A', 'Classic', 'YeShades', 'Patch', 'Blindfold', 'Monocle', 'SunsetChill', 'AstarFlame', 'ThugLife', 'VR'],

    'ARMOR_OLD': ['NA', 'SHIELDD', 'SHIELDpurple', 'SHIELDT', 'SHIELDgreen', 'SHIELDBLACK', 'N/A', 'SHIELDgree', 'SHIELD', 'SHIELDTosca'],
    'ARMOR': ['NA', 'ShieldPink', 'ShieldPurple', 'ShieldRedGold', 'ShieldGreen', 'ShieldBlack', 'N/A', 'ShieldLime', 'ShieldGrey', 'ShieldTeal'],
    
    'HAT_OLD': ['CowboyHat', 'SPARTAX', 'SPARTATOSCA', 'ASTRONAUTHELMET', 'REDCAP', 'SPARTABLACK', 'HORN', 'ORANGECAP', 'SPARTA', 'Beachhattosca', 'HORNGREEN', 'ForestRanger', 'darkBaseballHelmet', 'NA', 'YELLOWCAP', 'SPARTAORG', 'Haloangel', 'FLAME', 'Beachhat', 'HeadBand', 'POLICE', 'Chaplin', 'Beachhatpupr', 'GREENCAP', 'CROWN', 'einstein', 'Snapback', 'HORNYELLOW', 'CommandoCap', 'BaseballHelmet', 'FAZ', 'Piratecap', 'Beachhatpink', 'Policecap', 'BLUECAP', 'HORNMAGENTA', 'BLUEFIRE', 'blackkPiratecap', 'HORNBLUE'],
    'HAT': ['CowboyHat', 'SpartaPurple', 'SpartaTeal', 'AstronautHelmet', 'RedCap', 'SpartaBlack', 'HornRed', 'OrangeCap', 'SpartaGold', 'SunHatTeal', 'HornGreen', 'ForestRanger', 'BaseballHelmetDark', 'N/A', 'YellowCap', 'SpartaOrange', 'Halo', 'FlameOnRed', 'SunHatTan', 'HeadBand', 'Headwear', 'Chaplin', 'SunHatPurple', 'GreenCap', 'Crown', 'EinsteinHair', 'Snapback', 'HornYellow', 'Beret', 'BaseballHelmetLight', 'Fez', 'PirateDrakGrey', 'SunHatPink', 'PoliceHat', 'BlueCap', 'HornPink', 'FlameOnPurple', 'PirateBlack', 'HornBlue']
}

